service: devrook-be

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: ${env:REGION, 'us-west-2'}
  stage: ${opt:stage, 'dev'}
  environment:
    REGION: ${self:provider.region}
    SERVICE_NAME: "${self:service}-${self:provider.stage}"
    STAGE: "${self:provider.stage, dev}"
    REDIRECT_URL_AFTER_AUTHENTICATION: ${self:custom.REDIRECT_URL_AFTER_AUTHENTICATION.${opt:stage, dev}}
    s3MainBucket: ${self:custom.s3MainBucket}
  iamRoleStatements: ${file(./Resources/LambdaRole.yml)}

plugins:
  - serverless-pseudo-parameters
  - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-plugin-split-stacks

custom:
  userPoolName: "${self:service}-${self:provider.stage}"
  userPoolClientName: "${self:service}-user-pool-client-${self:provider.stage}"

  REDIRECT_URL_AFTER_AUTHENTICATION:
    prod: "https://your-domain-name-here.com/"
    dev: "https://your-domain-name-here.com/"

  splitStacks:
    perFunction: false
    perType: true
    perGroupFunction: true
    nestedStackCount: 20
  ##this stack count never should change if changed have to deploy it from scratch again  

  s3MainBucket: "${self:service}-main-bucket"

functions:
  hello:
    handler: handler.hello

resources:
  Resources:
    CognitoUserPool: ${file(./Resources/CognitoUserPool.yml)}
    CognitoUserPoolClient: ${file(./Resources/CognitoUserPoolClient.yml)}
    CognitoUserPooldomain: ${file(./Resources/CognitoUserPooldomain.yml)}
    CognitoIdentityPool: ${file(./Resources/CognitoIdentityPool.yml)}
    CognitoUnAuthorizedRole: ${file(./Resources/CognitoUnAuthorizedRole.yml)}
    CognitoAuthorizedRole: ${file(./Resources/CognitoAuthorizedRole.yml)}
    IdentityPoolRoleMapping: ${file(./Resources/IdentityPoolRoleMapping.yml)}
    CognitoUserPoolFacebookIdentityProvider: ${file(./Resources/CognitoUserPoolFacebookIdentityProvider.yml)}
    CognitoUserPoolGoogleIdentityProvider: ${file(./Resources/CognitoUserPoolGoogleIdentityProvider.yml)}
  
    # >>>>>>>>>>--S3 BUCKETS--<<<<<<<<<<< #
    S3MainBucket: ${file(./Resources/S3MainBucket.yml)} 
    # >>>>>>>>>>--DYNAMO DB TABLES--<<<<<<<<<<< #

  Outputs:
    CognitoUserPoolId:
      Value:
        Ref: CognitoUserPool
    CognitoUserPoolClientId:
      Value:
        Ref: CognitoUserPoolClient
    IdentityPoolId:
      Value: 
        Ref: CognitoIdentityPool           